package com.dtxx.mapper;

import com.dtxx.model.LawIncomingRetList;

public interface LawIncomingRetListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING_RET_LIST
     *
     * @mbg.generated
     */
    int insert(LawIncomingRetList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING_RET_LIST
     *
     * @mbg.generated
     */
    int insertSelective(LawIncomingRetList record);
}