package com.dtxx.mapper;

import com.dtxx.model.LawIncoming;
import com.dtxx.model.LawIncomingKey;
import com.dtxx.model.LawIncomingRet;

import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface LawIncomingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(LawIncomingKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING
     *
     * @mbg.generated
     */
    int insert(LawIncoming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING
     *
     * @mbg.generated
     */
    int insertSelective(LawIncoming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING
     *
     * @mbg.generated
     */
    LawIncoming selectByPrimaryKey(LawIncomingKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LawIncoming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LawIncoming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LawIncoming record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING
     *
     * @mbg.generated
     */
    List<LawIncoming> selectReading(LawIncomingKey key);

    List<LawIncoming> selectAll();
}