package com.dtxx.mapper;

import com.dtxx.model.LawIncomingList;

public interface LawIncomingListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING_LIST
     *
     * @mbg.generated
     */
    int insert(LawIncomingList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING_LIST
     *
     * @mbg.generated
     */
    int insertSelective(LawIncomingList record);
}