package com.dtxx.mapper;

import java.util.List;

import com.dtxx.model.LawIncomingRet;
import com.dtxx.model.LawIncomingRetKey;

public interface LawIncomingRetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING_RET
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(LawIncomingRetKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING_RET
     *
     * @mbg.generated
     */
    int insert(LawIncomingRet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING_RET
     *
     * @mbg.generated
     */
    int insertSelective(LawIncomingRet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING_RET
     *
     * @mbg.generated
     */
    LawIncomingRet selectByPrimaryKey(LawIncomingRetKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING_RET
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LawIncomingRet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING_RET
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LawIncomingRet record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_INCOMING_RET
     *
     * @mbg.generated
     */
    List<LawIncomingRet> selectReading(LawIncomingRetKey key);
}