package com.dtxx.mapper;

import com.dtxx.model.LawOutcomingList;

public interface LawOutcomingListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING_LIST
     *
     * @mbg.generated
     */
    int insert(LawOutcomingList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING_LIST
     *
     * @mbg.generated
     */
    int insertSelective(LawOutcomingList record);
}