package com.dtxx.mapper;

import com.dtxx.model.LawOutSysDataBase;

public interface LawOutSysDataBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long baseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
     *
     * @mbg.generated
     */
    int insert(LawOutSysDataBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
     *
     * @mbg.generated
     */
    int insertSelective(LawOutSysDataBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
     *
     * @mbg.generated
     */
    LawOutSysDataBase selectByPrimaryKey(Long baseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LawOutSysDataBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LawOutSysDataBase record);

	LawOutSysDataBase selectByPrimaryKey(LawOutSysDataBase lawOutSysDataBase);
}