package com.dtxx.mapper;

import java.util.List;

import com.dtxx.model.LawIncoming;
import com.dtxx.model.LawOutcoming;
import com.dtxx.model.LawOutcomingKey;

public interface LawOutcomingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(LawOutcomingKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING
     *
     * @mbg.generated
     */
    int insert(LawOutcoming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING
     *
     * @mbg.generated
     */
    int insertSelective(LawOutcoming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING
     *
     * @mbg.generated
     */
    LawOutcoming selectByPrimaryKey(LawOutcomingKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LawOutcoming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LawOutcoming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LawOutcoming record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING
     *
     * @mbg.generated
     */
    List<LawOutcoming> selectReading(LawOutcomingKey id);
    List<LawOutcoming> selectAll(String sourceSysCode);
}