package com.dtxx.mapper;

import java.util.List;

import com.dtxx.model.LawOutcoming;
import com.dtxx.model.LawOutcomingKey;
import com.dtxx.model.LawOutcomingRet;
import com.dtxx.model.LawOutcomingRetKey;

public interface LawOutcomingRetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING_RET
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(LawOutcomingRetKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING_RET
     *
     * @mbg.generated
     */
    int insert(LawOutcomingRet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING_RET
     *
     * @mbg.generated
     */
    int insertSelective(LawOutcomingRet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING_RET
     *
     * @mbg.generated
     */
    LawOutcomingRet selectByPrimaryKey(LawOutcomingRetKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING_RET
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LawOutcomingRet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING_RET
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LawOutcomingRet record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING
     *
     * @mbg.generated
     */
    List<LawOutcomingRet> selectReading(LawOutcomingRetKey id);
}