package com.dtxx.mapper;

import com.dtxx.model.LawOutcomingRetList;

public interface LawOutcomingRetListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING_RET_LIST
     *
     * @mbg.generated
     */
    int insert(LawOutcomingRetList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUTCOMING_RET_LIST
     *
     * @mbg.generated
     */
    int insertSelective(LawOutcomingRetList record);
}