
package com.dtxx.mapper;

import com.dtxx.model.LawOutSysDataMap;

public interface LawOutSysDataMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUT_SYS_DATA_MAP
     *
     * @mbg.generated
     */
    int insert(LawOutSysDataMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_OUT_SYS_DATA_MAP
     *
     * @mbg.generated
     */
    int insertSelective(LawOutSysDataMap record);
		/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LAW_OUT_SYS_DATA_MAP
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long mapId);



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LAW_OUT_SYS_DATA_MAP
	 * @mbg.generated
	 */
	LawOutSysDataMap selectByPrimaryKey(LawOutSysDataMap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LAW_OUT_SYS_DATA_MAP
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(LawOutSysDataMap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LAW_OUT_SYS_DATA_MAP
	 * @mbg.generated
	 */
	int updateByPrimaryKey(LawOutSysDataMap record);
}
