package com.dtxx.mapper;

import com.dtxx.model.LawSysSecretKey;

public interface LawSysSecretKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SYS_SECRET_KEY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long secretKeyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SYS_SECRET_KEY
     *
     * @mbg.generated
     */
    int insert(LawSysSecretKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SYS_SECRET_KEY
     *
     * @mbg.generated
     */
    int insertSelective(LawSysSecretKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SYS_SECRET_KEY
     *
     * @mbg.generated
     */
    LawSysSecretKey selectByPrimaryKey(String SYS_CODE);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SYS_SECRET_KEY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LawSysSecretKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SYS_SECRET_KEY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LawSysSecretKey record);
}