package com.dtxx.model;

import java.util.Date;

public class LawIncoming extends LawIncomingKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_INCOMING.INTF_CODE
     *
     * @mbg.generated
     */
    private String intfCode;

   

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_INCOMING.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;
//    private Integer attachCount;
//    private String errorMsg;
//    
//
//    public Integer getAttachCount() {
//		return attachCount;
//	}
//
//	public void setAttachCount(Integer attachCount) {
//		this.attachCount = attachCount;
//	}
//
//	public String getErrorMsg() {
//		return errorMsg;
//	}
//
//	public void setErrorMsg(String errorMsg) {
//		this.errorMsg = errorMsg;
//	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_INCOMING.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_INCOMING.JSON
     *
     * @mbg.generated
     */
    private String json;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_INCOMING.INTF_CODE
     *
     * @return the value of LAW_INCOMING.INTF_CODE
     *
     * @mbg.generated
     */
    public String getIntfCode() {
        return intfCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_INCOMING.INTF_CODE
     *
     * @param intfCode the value for LAW_INCOMING.INTF_CODE
     *
     * @mbg.generated
     */
    public void setIntfCode(String intfCode) {
        this.intfCode = intfCode == null ? null : intfCode.trim();
    }

   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_INCOMING.CREATION_DATE
     *
     * @return the value of LAW_INCOMING.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_INCOMING.CREATION_DATE
     *
     * @param creationDate the value for LAW_INCOMING.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_INCOMING.LAST_UPDATE_DATE
     *
     * @return the value of LAW_INCOMING.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_INCOMING.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for LAW_INCOMING.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_INCOMING.JSON
     *
     * @return the value of LAW_INCOMING.JSON
     *
     * @mbg.generated
     */
    public String getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_INCOMING.JSON
     *
     * @param json the value for LAW_INCOMING.JSON
     *
     * @mbg.generated
     */
    public void setJson(String json) {
        this.json = json == null ? null : json.trim();
    }
    
    
    private int attachCount;
    
    private String errorMsg;

	public int getAttachCount() {
		return attachCount;
	}

	public void setAttachCount(int attachCount) {
		this.attachCount = attachCount;
	}

	public String getErrorMsg() {
		return errorMsg;
	}

	public void setErrorMsg(String errorMsg) {
		this.errorMsg = errorMsg;
	}
    
    
}