package com.dtxx.model;

public class LawIncomingRetKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_INCOMING_RET.IN_ID
     *
     * @mbg.generated
     */
    private Integer inId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_INCOMING_RET.TARGET_SYS_CODE
     *
     * @mbg.generated
     */
    private String targetSysCode;
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column LAW_INCOMING_RET.STATUS
    *
    * @mbg.generated
    */
   private String status;
   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column LAW_INCOMING_RET.STATUS
    *
    * @return the value of LAW_INCOMING_RET.STATUS
    *
    * @mbg.generated
    */
   public String getStatus() {
       return status;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column LAW_INCOMING_RET.STATUS
    *
    * @param status the value for LAW_INCOMING_RET.STATUS
    *
    * @mbg.generated
    */
   public void setStatus(String status) {
       this.status = status == null ? null : status.trim();
   }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_INCOMING_RET.IN_ID
     *
     * @return the value of LAW_INCOMING_RET.IN_ID
     *
     * @mbg.generated
     */
    public Integer getInId() {
        return inId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_INCOMING_RET.IN_ID
     *
     * @param inId the value for LAW_INCOMING_RET.IN_ID
     *
     * @mbg.generated
     */
    public void setInId(Integer inId) {
        this.inId = inId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_INCOMING_RET.TARGET_SYS_CODE
     *
     * @return the value of LAW_INCOMING_RET.TARGET_SYS_CODE
     *
     * @mbg.generated
     */
    public String getTargetSysCode() {
        return targetSysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_INCOMING_RET.TARGET_SYS_CODE
     *
     * @param targetSysCode the value for LAW_INCOMING_RET.TARGET_SYS_CODE
     *
     * @mbg.generated
     */
    public void setTargetSysCode(String targetSysCode) {
        this.targetSysCode = targetSysCode == null ? null : targetSysCode.trim();
    }
    public LawIncomingRetKey(Integer inId, String targetSysCode) {
        this.inId = inId;
        this.targetSysCode = targetSysCode;
    }
    public LawIncomingRetKey(String targetSysCode) {
        this.targetSysCode = targetSysCode;
    }
    public LawIncomingRetKey() {
		// TODO Auto-generated constructor stub
	}
}