package com.dtxx.model;

import java.util.Date;

public class LawOutSysDataMap {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LAW_OUT_SYS_DATA_MAP.MAP_ID
	 * @mbg.generated
	 */
	private Long mapId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LAW_OUT_SYS_DATA_MAP.SYSCODE
	 * @mbg.generated
	 */
	private String syscode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LAW_OUT_SYS_DATA_MAP.TYPE
	 * @mbg.generated
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LAW_OUT_SYS_DATA_MAP.LAW_VALUE
	 * @mbg.generated
	 */
	private String lawValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LAW_OUT_SYS_DATA_MAP.MAP_VALUE
	 * @mbg.generated
	 */
	private String mapValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LAW_OUT_SYS_DATA_MAP.ATTRIBUTE1
	 * @mbg.generated
	 */
	private String attribute1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LAW_OUT_SYS_DATA_MAP.ATTRIBUTE2
	 * @mbg.generated
	 */
	private String attribute2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LAW_OUT_SYS_DATA_MAP.ATTRIBUTE3
	 * @mbg.generated
	 */
	private String attribute3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LAW_OUT_SYS_DATA_MAP.ATTRIBUTE4
	 * @mbg.generated
	 */
	private String attribute4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LAW_OUT_SYS_DATA_MAP.ATTRIBUTE5
	 * @mbg.generated
	 */
	private String attribute5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LAW_OUT_SYS_DATA_MAP.STATUS
	 * @mbg.generated
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LAW_OUT_SYS_DATA_MAP.CREATION_DATE
	 * @mbg.generated
	 */
	private Date creationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LAW_OUT_SYS_DATA_MAP.LAST_UPDATE_DATE
	 * @mbg.generated
	 */
	private Date lastUpdateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LAW_OUT_SYS_DATA_MAP.MAP_ID
	 * @return  the value of LAW_OUT_SYS_DATA_MAP.MAP_ID
	 * @mbg.generated
	 */
	public Long getMapId() {
		return mapId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LAW_OUT_SYS_DATA_MAP.MAP_ID
	 * @param mapId  the value for LAW_OUT_SYS_DATA_MAP.MAP_ID
	 * @mbg.generated
	 */
	public void setMapId(Long mapId) {
		this.mapId = mapId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LAW_OUT_SYS_DATA_MAP.SYSCODE
	 * @return  the value of LAW_OUT_SYS_DATA_MAP.SYSCODE
	 * @mbg.generated
	 */
	public String getSyscode() {
		return syscode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LAW_OUT_SYS_DATA_MAP.SYSCODE
	 * @param syscode  the value for LAW_OUT_SYS_DATA_MAP.SYSCODE
	 * @mbg.generated
	 */
	public void setSyscode(String syscode) {
		this.syscode = syscode == null ? null : syscode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LAW_OUT_SYS_DATA_MAP.TYPE
	 * @return  the value of LAW_OUT_SYS_DATA_MAP.TYPE
	 * @mbg.generated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LAW_OUT_SYS_DATA_MAP.TYPE
	 * @param type  the value for LAW_OUT_SYS_DATA_MAP.TYPE
	 * @mbg.generated
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LAW_OUT_SYS_DATA_MAP.LAW_VALUE
	 * @return  the value of LAW_OUT_SYS_DATA_MAP.LAW_VALUE
	 * @mbg.generated
	 */
	public String getLawValue() {
		return lawValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LAW_OUT_SYS_DATA_MAP.LAW_VALUE
	 * @param lawValue  the value for LAW_OUT_SYS_DATA_MAP.LAW_VALUE
	 * @mbg.generated
	 */
	public void setLawValue(String lawValue) {
		this.lawValue = lawValue == null ? null : lawValue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LAW_OUT_SYS_DATA_MAP.MAP_VALUE
	 * @return  the value of LAW_OUT_SYS_DATA_MAP.MAP_VALUE
	 * @mbg.generated
	 */
	public String getMapValue() {
		return mapValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LAW_OUT_SYS_DATA_MAP.MAP_VALUE
	 * @param mapValue  the value for LAW_OUT_SYS_DATA_MAP.MAP_VALUE
	 * @mbg.generated
	 */
	public void setMapValue(String mapValue) {
		this.mapValue = mapValue == null ? null : mapValue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LAW_OUT_SYS_DATA_MAP.ATTRIBUTE1
	 * @return  the value of LAW_OUT_SYS_DATA_MAP.ATTRIBUTE1
	 * @mbg.generated
	 */
	public String getAttribute1() {
		return attribute1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LAW_OUT_SYS_DATA_MAP.ATTRIBUTE1
	 * @param attribute1  the value for LAW_OUT_SYS_DATA_MAP.ATTRIBUTE1
	 * @mbg.generated
	 */
	public void setAttribute1(String attribute1) {
		this.attribute1 = attribute1 == null ? null : attribute1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LAW_OUT_SYS_DATA_MAP.ATTRIBUTE2
	 * @return  the value of LAW_OUT_SYS_DATA_MAP.ATTRIBUTE2
	 * @mbg.generated
	 */
	public String getAttribute2() {
		return attribute2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LAW_OUT_SYS_DATA_MAP.ATTRIBUTE2
	 * @param attribute2  the value for LAW_OUT_SYS_DATA_MAP.ATTRIBUTE2
	 * @mbg.generated
	 */
	public void setAttribute2(String attribute2) {
		this.attribute2 = attribute2 == null ? null : attribute2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LAW_OUT_SYS_DATA_MAP.ATTRIBUTE3
	 * @return  the value of LAW_OUT_SYS_DATA_MAP.ATTRIBUTE3
	 * @mbg.generated
	 */
	public String getAttribute3() {
		return attribute3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LAW_OUT_SYS_DATA_MAP.ATTRIBUTE3
	 * @param attribute3  the value for LAW_OUT_SYS_DATA_MAP.ATTRIBUTE3
	 * @mbg.generated
	 */
	public void setAttribute3(String attribute3) {
		this.attribute3 = attribute3 == null ? null : attribute3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LAW_OUT_SYS_DATA_MAP.ATTRIBUTE4
	 * @return  the value of LAW_OUT_SYS_DATA_MAP.ATTRIBUTE4
	 * @mbg.generated
	 */
	public String getAttribute4() {
		return attribute4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LAW_OUT_SYS_DATA_MAP.ATTRIBUTE4
	 * @param attribute4  the value for LAW_OUT_SYS_DATA_MAP.ATTRIBUTE4
	 * @mbg.generated
	 */
	public void setAttribute4(String attribute4) {
		this.attribute4 = attribute4 == null ? null : attribute4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LAW_OUT_SYS_DATA_MAP.ATTRIBUTE5
	 * @return  the value of LAW_OUT_SYS_DATA_MAP.ATTRIBUTE5
	 * @mbg.generated
	 */
	public String getAttribute5() {
		return attribute5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LAW_OUT_SYS_DATA_MAP.ATTRIBUTE5
	 * @param attribute5  the value for LAW_OUT_SYS_DATA_MAP.ATTRIBUTE5
	 * @mbg.generated
	 */
	public void setAttribute5(String attribute5) {
		this.attribute5 = attribute5 == null ? null : attribute5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LAW_OUT_SYS_DATA_MAP.STATUS
	 * @return  the value of LAW_OUT_SYS_DATA_MAP.STATUS
	 * @mbg.generated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LAW_OUT_SYS_DATA_MAP.STATUS
	 * @param status  the value for LAW_OUT_SYS_DATA_MAP.STATUS
	 * @mbg.generated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LAW_OUT_SYS_DATA_MAP.CREATION_DATE
	 * @return  the value of LAW_OUT_SYS_DATA_MAP.CREATION_DATE
	 * @mbg.generated
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LAW_OUT_SYS_DATA_MAP.CREATION_DATE
	 * @param creationDate  the value for LAW_OUT_SYS_DATA_MAP.CREATION_DATE
	 * @mbg.generated
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LAW_OUT_SYS_DATA_MAP.LAST_UPDATE_DATE
	 * @return  the value of LAW_OUT_SYS_DATA_MAP.LAST_UPDATE_DATE
	 * @mbg.generated
	 */
	public Date getLastUpdateDate() {
		return lastUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LAW_OUT_SYS_DATA_MAP.LAST_UPDATE_DATE
	 * @param lastUpdateDate  the value for LAW_OUT_SYS_DATA_MAP.LAST_UPDATE_DATE
	 * @mbg.generated
	 */
	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}
}