package com.dtxx.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LawOutSysDataBaseExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	public LawOutSysDataBaseExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andBaseIdIsNull() {
			addCriterion("BASE_ID is null");
			return (Criteria) this;
		}

		public Criteria andBaseIdIsNotNull() {
			addCriterion("BASE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andBaseIdEqualTo(Long value) {
			addCriterion("BASE_ID =", value, "baseId");
			return (Criteria) this;
		}

		public Criteria andBaseIdNotEqualTo(Long value) {
			addCriterion("BASE_ID <>", value, "baseId");
			return (Criteria) this;
		}

		public Criteria andBaseIdGreaterThan(Long value) {
			addCriterion("BASE_ID >", value, "baseId");
			return (Criteria) this;
		}

		public Criteria andBaseIdGreaterThanOrEqualTo(Long value) {
			addCriterion("BASE_ID >=", value, "baseId");
			return (Criteria) this;
		}

		public Criteria andBaseIdLessThan(Long value) {
			addCriterion("BASE_ID <", value, "baseId");
			return (Criteria) this;
		}

		public Criteria andBaseIdLessThanOrEqualTo(Long value) {
			addCriterion("BASE_ID <=", value, "baseId");
			return (Criteria) this;
		}

		public Criteria andBaseIdIn(List<Long> values) {
			addCriterion("BASE_ID in", values, "baseId");
			return (Criteria) this;
		}

		public Criteria andBaseIdNotIn(List<Long> values) {
			addCriterion("BASE_ID not in", values, "baseId");
			return (Criteria) this;
		}

		public Criteria andBaseIdBetween(Long value1, Long value2) {
			addCriterion("BASE_ID between", value1, value2, "baseId");
			return (Criteria) this;
		}

		public Criteria andBaseIdNotBetween(Long value1, Long value2) {
			addCriterion("BASE_ID not between", value1, value2, "baseId");
			return (Criteria) this;
		}

		public Criteria andSyscodeIsNull() {
			addCriterion("SYSCODE is null");
			return (Criteria) this;
		}

		public Criteria andSyscodeIsNotNull() {
			addCriterion("SYSCODE is not null");
			return (Criteria) this;
		}

		public Criteria andSyscodeEqualTo(String value) {
			addCriterion("SYSCODE =", value, "syscode");
			return (Criteria) this;
		}

		public Criteria andSyscodeNotEqualTo(String value) {
			addCriterion("SYSCODE <>", value, "syscode");
			return (Criteria) this;
		}

		public Criteria andSyscodeGreaterThan(String value) {
			addCriterion("SYSCODE >", value, "syscode");
			return (Criteria) this;
		}

		public Criteria andSyscodeGreaterThanOrEqualTo(String value) {
			addCriterion("SYSCODE >=", value, "syscode");
			return (Criteria) this;
		}

		public Criteria andSyscodeLessThan(String value) {
			addCriterion("SYSCODE <", value, "syscode");
			return (Criteria) this;
		}

		public Criteria andSyscodeLessThanOrEqualTo(String value) {
			addCriterion("SYSCODE <=", value, "syscode");
			return (Criteria) this;
		}

		public Criteria andSyscodeLike(String value) {
			addCriterion("SYSCODE like", value, "syscode");
			return (Criteria) this;
		}

		public Criteria andSyscodeNotLike(String value) {
			addCriterion("SYSCODE not like", value, "syscode");
			return (Criteria) this;
		}

		public Criteria andSyscodeIn(List<String> values) {
			addCriterion("SYSCODE in", values, "syscode");
			return (Criteria) this;
		}

		public Criteria andSyscodeNotIn(List<String> values) {
			addCriterion("SYSCODE not in", values, "syscode");
			return (Criteria) this;
		}

		public Criteria andSyscodeBetween(String value1, String value2) {
			addCriterion("SYSCODE between", value1, value2, "syscode");
			return (Criteria) this;
		}

		public Criteria andSyscodeNotBetween(String value1, String value2) {
			addCriterion("SYSCODE not between", value1, value2, "syscode");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("TYPE is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(String value) {
			addCriterion("TYPE =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("TYPE <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(String value) {
			addCriterion("TYPE >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("TYPE >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(String value) {
			addCriterion("TYPE <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("TYPE <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLike(String value) {
			addCriterion("TYPE like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotLike(String value) {
			addCriterion("TYPE not like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<String> values) {
			addCriterion("TYPE in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("TYPE not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("TYPE between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("TYPE not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("CODE is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("CODE is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("CODE =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("CODE <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("CODE >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("CODE >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("CODE <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("CODE <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("CODE like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("CODE not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("CODE in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("CODE not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("CODE between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("CODE not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andParentIsNull() {
			addCriterion("PARENT is null");
			return (Criteria) this;
		}

		public Criteria andParentIsNotNull() {
			addCriterion("PARENT is not null");
			return (Criteria) this;
		}

		public Criteria andParentEqualTo(String value) {
			addCriterion("PARENT =", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentNotEqualTo(String value) {
			addCriterion("PARENT <>", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentGreaterThan(String value) {
			addCriterion("PARENT >", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentGreaterThanOrEqualTo(String value) {
			addCriterion("PARENT >=", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentLessThan(String value) {
			addCriterion("PARENT <", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentLessThanOrEqualTo(String value) {
			addCriterion("PARENT <=", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentLike(String value) {
			addCriterion("PARENT like", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentNotLike(String value) {
			addCriterion("PARENT not like", value, "parent");
			return (Criteria) this;
		}

		public Criteria andParentIn(List<String> values) {
			addCriterion("PARENT in", values, "parent");
			return (Criteria) this;
		}

		public Criteria andParentNotIn(List<String> values) {
			addCriterion("PARENT not in", values, "parent");
			return (Criteria) this;
		}

		public Criteria andParentBetween(String value1, String value2) {
			addCriterion("PARENT between", value1, value2, "parent");
			return (Criteria) this;
		}

		public Criteria andParentNotBetween(String value1, String value2) {
			addCriterion("PARENT not between", value1, value2, "parent");
			return (Criteria) this;
		}

		public Criteria andAttribute1IsNull() {
			addCriterion("ATTRIBUTE1 is null");
			return (Criteria) this;
		}

		public Criteria andAttribute1IsNotNull() {
			addCriterion("ATTRIBUTE1 is not null");
			return (Criteria) this;
		}

		public Criteria andAttribute1EqualTo(String value) {
			addCriterion("ATTRIBUTE1 =", value, "attribute1");
			return (Criteria) this;
		}

		public Criteria andAttribute1NotEqualTo(String value) {
			addCriterion("ATTRIBUTE1 <>", value, "attribute1");
			return (Criteria) this;
		}

		public Criteria andAttribute1GreaterThan(String value) {
			addCriterion("ATTRIBUTE1 >", value, "attribute1");
			return (Criteria) this;
		}

		public Criteria andAttribute1GreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE1 >=", value, "attribute1");
			return (Criteria) this;
		}

		public Criteria andAttribute1LessThan(String value) {
			addCriterion("ATTRIBUTE1 <", value, "attribute1");
			return (Criteria) this;
		}

		public Criteria andAttribute1LessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE1 <=", value, "attribute1");
			return (Criteria) this;
		}

		public Criteria andAttribute1Like(String value) {
			addCriterion("ATTRIBUTE1 like", value, "attribute1");
			return (Criteria) this;
		}

		public Criteria andAttribute1NotLike(String value) {
			addCriterion("ATTRIBUTE1 not like", value, "attribute1");
			return (Criteria) this;
		}

		public Criteria andAttribute1In(List<String> values) {
			addCriterion("ATTRIBUTE1 in", values, "attribute1");
			return (Criteria) this;
		}

		public Criteria andAttribute1NotIn(List<String> values) {
			addCriterion("ATTRIBUTE1 not in", values, "attribute1");
			return (Criteria) this;
		}

		public Criteria andAttribute1Between(String value1, String value2) {
			addCriterion("ATTRIBUTE1 between", value1, value2, "attribute1");
			return (Criteria) this;
		}

		public Criteria andAttribute1NotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE1 not between", value1, value2, "attribute1");
			return (Criteria) this;
		}

		public Criteria andAttribute2IsNull() {
			addCriterion("ATTRIBUTE2 is null");
			return (Criteria) this;
		}

		public Criteria andAttribute2IsNotNull() {
			addCriterion("ATTRIBUTE2 is not null");
			return (Criteria) this;
		}

		public Criteria andAttribute2EqualTo(String value) {
			addCriterion("ATTRIBUTE2 =", value, "attribute2");
			return (Criteria) this;
		}

		public Criteria andAttribute2NotEqualTo(String value) {
			addCriterion("ATTRIBUTE2 <>", value, "attribute2");
			return (Criteria) this;
		}

		public Criteria andAttribute2GreaterThan(String value) {
			addCriterion("ATTRIBUTE2 >", value, "attribute2");
			return (Criteria) this;
		}

		public Criteria andAttribute2GreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE2 >=", value, "attribute2");
			return (Criteria) this;
		}

		public Criteria andAttribute2LessThan(String value) {
			addCriterion("ATTRIBUTE2 <", value, "attribute2");
			return (Criteria) this;
		}

		public Criteria andAttribute2LessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE2 <=", value, "attribute2");
			return (Criteria) this;
		}

		public Criteria andAttribute2Like(String value) {
			addCriterion("ATTRIBUTE2 like", value, "attribute2");
			return (Criteria) this;
		}

		public Criteria andAttribute2NotLike(String value) {
			addCriterion("ATTRIBUTE2 not like", value, "attribute2");
			return (Criteria) this;
		}

		public Criteria andAttribute2In(List<String> values) {
			addCriterion("ATTRIBUTE2 in", values, "attribute2");
			return (Criteria) this;
		}

		public Criteria andAttribute2NotIn(List<String> values) {
			addCriterion("ATTRIBUTE2 not in", values, "attribute2");
			return (Criteria) this;
		}

		public Criteria andAttribute2Between(String value1, String value2) {
			addCriterion("ATTRIBUTE2 between", value1, value2, "attribute2");
			return (Criteria) this;
		}

		public Criteria andAttribute2NotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE2 not between", value1, value2, "attribute2");
			return (Criteria) this;
		}

		public Criteria andAttribute3IsNull() {
			addCriterion("ATTRIBUTE3 is null");
			return (Criteria) this;
		}

		public Criteria andAttribute3IsNotNull() {
			addCriterion("ATTRIBUTE3 is not null");
			return (Criteria) this;
		}

		public Criteria andAttribute3EqualTo(String value) {
			addCriterion("ATTRIBUTE3 =", value, "attribute3");
			return (Criteria) this;
		}

		public Criteria andAttribute3NotEqualTo(String value) {
			addCriterion("ATTRIBUTE3 <>", value, "attribute3");
			return (Criteria) this;
		}

		public Criteria andAttribute3GreaterThan(String value) {
			addCriterion("ATTRIBUTE3 >", value, "attribute3");
			return (Criteria) this;
		}

		public Criteria andAttribute3GreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE3 >=", value, "attribute3");
			return (Criteria) this;
		}

		public Criteria andAttribute3LessThan(String value) {
			addCriterion("ATTRIBUTE3 <", value, "attribute3");
			return (Criteria) this;
		}

		public Criteria andAttribute3LessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE3 <=", value, "attribute3");
			return (Criteria) this;
		}

		public Criteria andAttribute3Like(String value) {
			addCriterion("ATTRIBUTE3 like", value, "attribute3");
			return (Criteria) this;
		}

		public Criteria andAttribute3NotLike(String value) {
			addCriterion("ATTRIBUTE3 not like", value, "attribute3");
			return (Criteria) this;
		}

		public Criteria andAttribute3In(List<String> values) {
			addCriterion("ATTRIBUTE3 in", values, "attribute3");
			return (Criteria) this;
		}

		public Criteria andAttribute3NotIn(List<String> values) {
			addCriterion("ATTRIBUTE3 not in", values, "attribute3");
			return (Criteria) this;
		}

		public Criteria andAttribute3Between(String value1, String value2) {
			addCriterion("ATTRIBUTE3 between", value1, value2, "attribute3");
			return (Criteria) this;
		}

		public Criteria andAttribute3NotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE3 not between", value1, value2, "attribute3");
			return (Criteria) this;
		}

		public Criteria andAttribute4IsNull() {
			addCriterion("ATTRIBUTE4 is null");
			return (Criteria) this;
		}

		public Criteria andAttribute4IsNotNull() {
			addCriterion("ATTRIBUTE4 is not null");
			return (Criteria) this;
		}

		public Criteria andAttribute4EqualTo(String value) {
			addCriterion("ATTRIBUTE4 =", value, "attribute4");
			return (Criteria) this;
		}

		public Criteria andAttribute4NotEqualTo(String value) {
			addCriterion("ATTRIBUTE4 <>", value, "attribute4");
			return (Criteria) this;
		}

		public Criteria andAttribute4GreaterThan(String value) {
			addCriterion("ATTRIBUTE4 >", value, "attribute4");
			return (Criteria) this;
		}

		public Criteria andAttribute4GreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE4 >=", value, "attribute4");
			return (Criteria) this;
		}

		public Criteria andAttribute4LessThan(String value) {
			addCriterion("ATTRIBUTE4 <", value, "attribute4");
			return (Criteria) this;
		}

		public Criteria andAttribute4LessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE4 <=", value, "attribute4");
			return (Criteria) this;
		}

		public Criteria andAttribute4Like(String value) {
			addCriterion("ATTRIBUTE4 like", value, "attribute4");
			return (Criteria) this;
		}

		public Criteria andAttribute4NotLike(String value) {
			addCriterion("ATTRIBUTE4 not like", value, "attribute4");
			return (Criteria) this;
		}

		public Criteria andAttribute4In(List<String> values) {
			addCriterion("ATTRIBUTE4 in", values, "attribute4");
			return (Criteria) this;
		}

		public Criteria andAttribute4NotIn(List<String> values) {
			addCriterion("ATTRIBUTE4 not in", values, "attribute4");
			return (Criteria) this;
		}

		public Criteria andAttribute4Between(String value1, String value2) {
			addCriterion("ATTRIBUTE4 between", value1, value2, "attribute4");
			return (Criteria) this;
		}

		public Criteria andAttribute4NotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE4 not between", value1, value2, "attribute4");
			return (Criteria) this;
		}

		public Criteria andAttribute5IsNull() {
			addCriterion("ATTRIBUTE5 is null");
			return (Criteria) this;
		}

		public Criteria andAttribute5IsNotNull() {
			addCriterion("ATTRIBUTE5 is not null");
			return (Criteria) this;
		}

		public Criteria andAttribute5EqualTo(String value) {
			addCriterion("ATTRIBUTE5 =", value, "attribute5");
			return (Criteria) this;
		}

		public Criteria andAttribute5NotEqualTo(String value) {
			addCriterion("ATTRIBUTE5 <>", value, "attribute5");
			return (Criteria) this;
		}

		public Criteria andAttribute5GreaterThan(String value) {
			addCriterion("ATTRIBUTE5 >", value, "attribute5");
			return (Criteria) this;
		}

		public Criteria andAttribute5GreaterThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE5 >=", value, "attribute5");
			return (Criteria) this;
		}

		public Criteria andAttribute5LessThan(String value) {
			addCriterion("ATTRIBUTE5 <", value, "attribute5");
			return (Criteria) this;
		}

		public Criteria andAttribute5LessThanOrEqualTo(String value) {
			addCriterion("ATTRIBUTE5 <=", value, "attribute5");
			return (Criteria) this;
		}

		public Criteria andAttribute5Like(String value) {
			addCriterion("ATTRIBUTE5 like", value, "attribute5");
			return (Criteria) this;
		}

		public Criteria andAttribute5NotLike(String value) {
			addCriterion("ATTRIBUTE5 not like", value, "attribute5");
			return (Criteria) this;
		}

		public Criteria andAttribute5In(List<String> values) {
			addCriterion("ATTRIBUTE5 in", values, "attribute5");
			return (Criteria) this;
		}

		public Criteria andAttribute5NotIn(List<String> values) {
			addCriterion("ATTRIBUTE5 not in", values, "attribute5");
			return (Criteria) this;
		}

		public Criteria andAttribute5Between(String value1, String value2) {
			addCriterion("ATTRIBUTE5 between", value1, value2, "attribute5");
			return (Criteria) this;
		}

		public Criteria andAttribute5NotBetween(String value1, String value2) {
			addCriterion("ATTRIBUTE5 not between", value1, value2, "attribute5");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreationDateIsNull() {
			addCriterion("CREATION_DATE is null");
			return (Criteria) this;
		}

		public Criteria andCreationDateIsNotNull() {
			addCriterion("CREATION_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andCreationDateEqualTo(Date value) {
			addCriterion("CREATION_DATE =", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateNotEqualTo(Date value) {
			addCriterion("CREATION_DATE <>", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateGreaterThan(Date value) {
			addCriterion("CREATION_DATE >", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATION_DATE >=", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateLessThan(Date value) {
			addCriterion("CREATION_DATE <", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateLessThanOrEqualTo(Date value) {
			addCriterion("CREATION_DATE <=", value, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateIn(List<Date> values) {
			addCriterion("CREATION_DATE in", values, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateNotIn(List<Date> values) {
			addCriterion("CREATION_DATE not in", values, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateBetween(Date value1, Date value2) {
			addCriterion("CREATION_DATE between", value1, value2, "creationDate");
			return (Criteria) this;
		}

		public Criteria andCreationDateNotBetween(Date value1, Date value2) {
			addCriterion("CREATION_DATE not between", value1, value2, "creationDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateIsNull() {
			addCriterion("LAST_UPDATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateIsNotNull() {
			addCriterion("LAST_UPDATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateEqualTo(Date value) {
			addCriterion("LAST_UPDATE_DATE =", value, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateNotEqualTo(Date value) {
			addCriterion("LAST_UPDATE_DATE <>", value, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateGreaterThan(Date value) {
			addCriterion("LAST_UPDATE_DATE >", value, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("LAST_UPDATE_DATE >=", value, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateLessThan(Date value) {
			addCriterion("LAST_UPDATE_DATE <", value, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("LAST_UPDATE_DATE <=", value, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateIn(List<Date> values) {
			addCriterion("LAST_UPDATE_DATE in", values, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateNotIn(List<Date> values) {
			addCriterion("LAST_UPDATE_DATE not in", values, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
			addCriterion("LAST_UPDATE_DATE between", value1, value2, "lastUpdateDate");
			return (Criteria) this;
		}

		public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("LAST_UPDATE_DATE not between", value1, value2, "lastUpdateDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table LAW_OUT_SYS_DATA_BASE
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LAW_OUT_SYS_DATA_BASE
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}