package com.dtxx.model;

import java.util.Date;

public class LawOutSysDataBase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_OUT_SYS_DATA_BASE.BASE_ID
     *
     * @mbg.generated
     */
    private Long baseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_OUT_SYS_DATA_BASE.SYSCODE
     *
     * @mbg.generated
     */
    private String syscode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_OUT_SYS_DATA_BASE.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_OUT_SYS_DATA_BASE.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_OUT_SYS_DATA_BASE.CODE
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_OUT_SYS_DATA_BASE.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_OUT_SYS_DATA_BASE.PARENT
     *
     * @mbg.generated
     */
    private String parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_OUT_SYS_DATA_BASE.ATTRIBUTE1
     *
     * @mbg.generated
     */
    private String attribute1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_OUT_SYS_DATA_BASE.ATTRIBUTE2
     *
     * @mbg.generated
     */
    private String attribute2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_OUT_SYS_DATA_BASE.ATTRIBUTE3
     *
     * @mbg.generated
     */
    private String attribute3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_OUT_SYS_DATA_BASE.ATTRIBUTE4
     *
     * @mbg.generated
     */
    private String attribute4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_OUT_SYS_DATA_BASE.ATTRIBUTE5
     *
     * @mbg.generated
     */
    private String attribute5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_OUT_SYS_DATA_BASE.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_OUT_SYS_DATA_BASE.CREATION_DATE
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_OUT_SYS_DATA_BASE.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_OUT_SYS_DATA_BASE.BASE_ID
     *
     * @return the value of LAW_OUT_SYS_DATA_BASE.BASE_ID
     *
     * @mbg.generated
     */
    public Long getBaseId() {
        return baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_OUT_SYS_DATA_BASE.BASE_ID
     *
     * @param baseId the value for LAW_OUT_SYS_DATA_BASE.BASE_ID
     *
     * @mbg.generated
     */
    public void setBaseId(Long baseId) {
        this.baseId = baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_OUT_SYS_DATA_BASE.SYSCODE
     *
     * @return the value of LAW_OUT_SYS_DATA_BASE.SYSCODE
     *
     * @mbg.generated
     */
    public String getSyscode() {
        return syscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_OUT_SYS_DATA_BASE.SYSCODE
     *
     * @param syscode the value for LAW_OUT_SYS_DATA_BASE.SYSCODE
     *
     * @mbg.generated
     */
    public void setSyscode(String syscode) {
        this.syscode = syscode == null ? null : syscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_OUT_SYS_DATA_BASE.TYPE
     *
     * @return the value of LAW_OUT_SYS_DATA_BASE.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_OUT_SYS_DATA_BASE.TYPE
     *
     * @param type the value for LAW_OUT_SYS_DATA_BASE.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_OUT_SYS_DATA_BASE.ID
     *
     * @return the value of LAW_OUT_SYS_DATA_BASE.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_OUT_SYS_DATA_BASE.ID
     *
     * @param id the value for LAW_OUT_SYS_DATA_BASE.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_OUT_SYS_DATA_BASE.CODE
     *
     * @return the value of LAW_OUT_SYS_DATA_BASE.CODE
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_OUT_SYS_DATA_BASE.CODE
     *
     * @param code the value for LAW_OUT_SYS_DATA_BASE.CODE
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_OUT_SYS_DATA_BASE.NAME
     *
     * @return the value of LAW_OUT_SYS_DATA_BASE.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_OUT_SYS_DATA_BASE.NAME
     *
     * @param name the value for LAW_OUT_SYS_DATA_BASE.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_OUT_SYS_DATA_BASE.PARENT
     *
     * @return the value of LAW_OUT_SYS_DATA_BASE.PARENT
     *
     * @mbg.generated
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_OUT_SYS_DATA_BASE.PARENT
     *
     * @param parent the value for LAW_OUT_SYS_DATA_BASE.PARENT
     *
     * @mbg.generated
     */
    public void setParent(String parent) {
        this.parent = parent == null ? null : parent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_OUT_SYS_DATA_BASE.ATTRIBUTE1
     *
     * @return the value of LAW_OUT_SYS_DATA_BASE.ATTRIBUTE1
     *
     * @mbg.generated
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_OUT_SYS_DATA_BASE.ATTRIBUTE1
     *
     * @param attribute1 the value for LAW_OUT_SYS_DATA_BASE.ATTRIBUTE1
     *
     * @mbg.generated
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1 == null ? null : attribute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_OUT_SYS_DATA_BASE.ATTRIBUTE2
     *
     * @return the value of LAW_OUT_SYS_DATA_BASE.ATTRIBUTE2
     *
     * @mbg.generated
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_OUT_SYS_DATA_BASE.ATTRIBUTE2
     *
     * @param attribute2 the value for LAW_OUT_SYS_DATA_BASE.ATTRIBUTE2
     *
     * @mbg.generated
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2 == null ? null : attribute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_OUT_SYS_DATA_BASE.ATTRIBUTE3
     *
     * @return the value of LAW_OUT_SYS_DATA_BASE.ATTRIBUTE3
     *
     * @mbg.generated
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_OUT_SYS_DATA_BASE.ATTRIBUTE3
     *
     * @param attribute3 the value for LAW_OUT_SYS_DATA_BASE.ATTRIBUTE3
     *
     * @mbg.generated
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3 == null ? null : attribute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_OUT_SYS_DATA_BASE.ATTRIBUTE4
     *
     * @return the value of LAW_OUT_SYS_DATA_BASE.ATTRIBUTE4
     *
     * @mbg.generated
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_OUT_SYS_DATA_BASE.ATTRIBUTE4
     *
     * @param attribute4 the value for LAW_OUT_SYS_DATA_BASE.ATTRIBUTE4
     *
     * @mbg.generated
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4 == null ? null : attribute4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_OUT_SYS_DATA_BASE.ATTRIBUTE5
     *
     * @return the value of LAW_OUT_SYS_DATA_BASE.ATTRIBUTE5
     *
     * @mbg.generated
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_OUT_SYS_DATA_BASE.ATTRIBUTE5
     *
     * @param attribute5 the value for LAW_OUT_SYS_DATA_BASE.ATTRIBUTE5
     *
     * @mbg.generated
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5 == null ? null : attribute5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_OUT_SYS_DATA_BASE.STATUS
     *
     * @return the value of LAW_OUT_SYS_DATA_BASE.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_OUT_SYS_DATA_BASE.STATUS
     *
     * @param status the value for LAW_OUT_SYS_DATA_BASE.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_OUT_SYS_DATA_BASE.CREATION_DATE
     *
     * @return the value of LAW_OUT_SYS_DATA_BASE.CREATION_DATE
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_OUT_SYS_DATA_BASE.CREATION_DATE
     *
     * @param creationDate the value for LAW_OUT_SYS_DATA_BASE.CREATION_DATE
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_OUT_SYS_DATA_BASE.LAST_UPDATE_DATE
     *
     * @return the value of LAW_OUT_SYS_DATA_BASE.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_OUT_SYS_DATA_BASE.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for LAW_OUT_SYS_DATA_BASE.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}